### PR TITLE
Adapted ONNXRuntime to O2

### PR DESCRIPTION
**Pull request by saganatt**
Ciao @ktf 

here are all ONNX changes.

### CODE REVIEW

**Comment by ktf** [comment]
v1.7.2-alice1 is now available with your changes.

**Comment by ktf** [comment]
Can we move the cmake changes to O2 and drop the need for changes WRT upstream?

**Comment by saganatt** [comment]
Ciao, I will check soon how it works but rather not today.

**Comment by saganatt** [comment]
Ciao,
the CMake changes are only:
- creation of `ONNXRuntime::ONNXRuntimeConfig.cmake` and `ONNXRuntime::ONNXRuntimeVersion.cmake` files
- additional command in `onnxruntime.cmake` to install these 2 new files
I did it so as ONNXRuntime can be found during compilation of O2/O2Physics. I couldn't find an alternative back then.
Do you know a workaround? I.e., is it possible to call something straight from O2 cmake files, that would magically find the ONNXRuntime package?

**Comment by saganatt** [comment]
There are also changes in CMakeLists.txt which seem more complicated.
But also a much more recent ONNXRuntime, which I tried to use for better IoBinding, has CMakeLists.txt totally rewritten, so I would anyways work on the newest CMakeLists.txt. Back then, I couldn't figure out how to modify the new CMakeLists.txt in a way that would make it compilable with aliBuild... The dependencies and their management changed way too much.

**Pull request merged**
